In [1]:
import pandas as pd

base_price = 810

clients = pd.DataFrame({
    "вік": [19, 23, 27, 31, 36, 42, 48, 53, 61, 68],
    "дохід": [18000, 24000, 32000, 28000, 45000,
              52000, 39000, 61000, 47000, 70000],
    "кількість": [2, 3, 4, 3, 5, 2, 3, 4, 2, 3],
    "місто_доставки": [
        "Дніпро", "Київ", "Львів", "Дніпро", "Одеса",
        "Київ", "Дніпро", "Львів", "Одеса", "Дніпро"
    ]
})

print("Варіант 5 — Дніпро")
clients

Варіант 5 — Дніпро

   вік  дохід  кількість місто_доставки
0   19  18000          2         Дніпро
1   23  24000          3           Київ
2   27  32000          4          Львів
3   31  28000          3         Дніпро
4   36  45000          5          Одеса
5   42  52000          2           Київ
6   48  39000          3         Дніпро
7   53  61000          4          Львів
8   61  47000          2          Одеса
9   68  70000          3         Дніпро

In [2]:
clients["сума_замовлення"] = (
    base_price * clients["кількість"]
)

clients["частка_доходу"] = (
    clients["сума_замовлення"] / clients["дохід"]
)

clients

   вік  дохід  кількість місто_доставки  сума_замовлення  частка_доходу
0   19  18000          2         Дніпро             1620       0.090000
1   23  24000          3           Київ             2430       0.101250
2   27  32000          4          Львів             3240       0.101250
3   31  28000          3         Дніпро             2430       0.086786
4   36  45000          5          Одеса             4050       0.090000
5   42  52000          2           Київ             1620       0.031154
6   48  39000          3         Дніпро             2430       0.062308
7   53  61000          4          Львів             3240       0.053115
8   61  47000          2          Одеса             1620       0.034468
9   68  70000          3         Дніпро             2430       0.034714

In [3]:
clients[
    ["дохід", "кількість", "сума_замовлення", "частка_доходу"]
]

   дохід  кількість  сума_замовлення  частка_доходу
0  18000          2             1620       0.090000
1  24000          3             2430       0.101250
2  32000          4             3240       0.101250
3  28000          3             2430       0.086786
4  45000          5             4050       0.090000
5  52000          2             1620       0.031154
6  39000          3             2430       0.062308
7  61000          4             3240       0.053115
8  47000          2             1620       0.034468
9  70000          3             2430       0.034714

Частка доходу є кориснішою для аналізу поведінки клієнта,
оскільки вона показує, яку частину свого місячного доходу
клієнт витрачає на замовлення.

Однакова сума замовлення може мати різне значення для
клієнтів із різним доходом. Наприклад, витрата 3000 грн
буде більш суттєвою для клієнта з доходом 18000 грн,
ніж для клієнта з доходом 70000 грн.

Тому частка доходу дозволяє краще порівнювати клієнтів
із різним рівнем доходу.

In [4]:
clients["вік_cut"] = pd.cut(
    clients["вік"],
    bins=3
)

print("Групи через cut:")
print(clients["вік_cut"].value_counts().sort_index())

Групи через cut:
вік_cut
(18.951, 35.333]    4
(35.333, 51.667]    3
(51.667, 68.0]      3
Name: count, dtype: int64

In [5]:
clients["вік_qcut"] = pd.qcut(
    clients["вік"],
    q=3
)

print("Групи через qcut:")
print(clients["вік_qcut"].value_counts().sort_index())

Групи через qcut:
вік_qcut
(18.999, 31.0]    3
(31.0, 48.0]      3
(48.0, 68.0]      4
Name: count, dtype: int64

In [6]:
print("CUT:")
print(clients["вік_cut"].value_counts().sort_index())

print("\nQCUT:")
print(clients["вік_qcut"].value_counts().sort_index())

CUT:
вік_cut
(18.951, 35.333]    4
(35.333, 51.667]    3
(51.667, 68.0]      3
Name: count, dtype: int64

QCUT:
вік_qcut
(18.999, 31.0]    3
(31.0, 48.0]      3
(48.0, 68.0]      4
Name: count, dtype: int64

pd.cut() та pd.qcut() по-різному формують групи.

pd.cut() розділяє весь діапазон значень віку на інтервали
приблизно однакової ширини. Через це кількість клієнтів
у кожному інтервалі може бути різною.

pd.qcut() формує межі груп на основі квантилів, щоб
кількість спостережень у групах була приблизно однаковою.
Тому ширина отриманих інтервалів може відрізнятися.

Отже, cut орієнтується на ширину інтервалів, а qcut —
на кількість спостережень у них.

In [10]:
clients["вік_minmax"] = (
    (clients["вік"] - clients["вік"].min()) /
    (clients["вік"].max() - clients["вік"].min())
)

clients["дохід_minmax"] = (
    (clients["дохід"] - clients["дохід"].min()) /
    (clients["дохід"].max() - clients["дохід"].min())
)

In [13]:
clients["вік_z"] = (
    (clients["вік"] - clients["вік"].mean()) /
    clients["вік"].std()
)

clients["дохід_z"] = (
    (clients["дохід"] - clients["дохід"].mean()) /
    clients["дохід"].std()
)

In [14]:
clients[[
    "вік",
    "дохід",
    "вік_minmax",
    "дохід_minmax",
    "вік_z",
    "дохід_z"
]].head()

   вік  дохід  вік_minmax  дохід_minmax     вік_z   дохід_z
0   19  18000    0.000000      0.000000 -1.320848 -1.421011
1   23  24000    0.081633      0.115385 -1.078491 -1.059737
2   27  32000    0.163265      0.269231 -0.836133 -0.578038
3   31  28000    0.244898      0.192308 -0.593776 -0.818888
4   36  45000    0.346939      0.519231 -0.290829  0.204722

До масштабування вік і дохід мають дуже різні масштаби.

Вік вимірюється десятками років, а дохід — десятками
тисяч гривень. Через це в методах, чутливих до масштабу,
дохід міг би мати значно більший вплив лише через свої
більші числові значення.

Min-max нормалізація приводить значення до діапазону
від 0 до 1.

Z-стандартизація показує, на скільки стандартних
відхилень значення знаходиться від середнього.

Після масштабування змінні можна коректніше використовувати
разом у методах, чутливих до масштабу.

In [15]:
city_dummies = pd.get_dummies(
    clients["місто_доставки"],
    prefix="місто"
)

city_dummies

   місто_Дніпро  місто_Київ  місто_Львів  місто_Одеса
0          True       False        False        False
1         False        True        False        False
2         False       False         True        False
3          True       False        False        False
4         False       False        False         True
5         False        True        False        False
6          True       False        False        False
7         False       False         True        False
8         False       False        False         True
9          True       False        False        False

In [17]:
clients = pd.concat(
    [clients, city_dummies],
    axis=1
)

clients

,вік,дохід,кількість,місто_доставки,сума_замовлення,частка_доходу,вік_cut,вік_qcut,вік_minmax,дохід_minmax,вік_z,дохід_z,місто_Дніпро,місто_Київ,місто_Львів,місто_Одеса
0,19,18000,2,Дніпро,1620,0.090000,"(18.951, 35.333]","(18.999, 31.0]",0.000000,0.000000,-1.320848,-1.421011,True,False,False,False
1,23,24000,3,Київ,2430,0.101250,"(18.951, 35.333]","(18.999, 31.0]",0.081633,0.115385,-1.078491,-1.059737,False,True,False,False
2,27,32000,4,Львів,3240,0.101250,"(18.951, 35.333]","(18.999, 31.0]",0.163265,0.269231,-0.836133,-0.578038,False,False,True,False
3,31,28000,3,Дніпро,2430,0.086786,"(18.951, 35.333]","(31.0, 48.0]",0.244898,0.192308,-0.593776,-0.818888,True,False,False,False
4,36,45000,5,Одеса,4050,0.090000,"(35.333, 51.667]","(31.0, 48.0]",0.346939,0.519231,-0.290829,0.204722,False,False,False,True
5,42,52000,2,Київ,1620,0.031154,"(35.333, 51.667]","(31.0, 48.0]",0.469388,0.653846,0.072707,0.626208,False,True,False,False
6,48,39000,3,Дніпро,2430,0.062308,"(35.333, 51.667]","(48.0, 68.0]",0.591837,0.403846,0.436243,-0.156552,True,False,False,False
7,53,61000,4,Львів,3240,0.053115,"(51.667, 68.0]","(48.0, 68.0]",0.693878,0.826923,0.739190,1.168119,False,False,True,False
8,61,47000,2,Одеса,1620,0.034468,"(51.667, 68.0]","(48.0, 68.0]",0.857143,0.557692,1.223905,0.325147,False,False,False,True
9,68,70000,3,Дніпро,2430,0.034714,"(51.667, 68.0]","(48.0, 68.0]",1.000000,1.000000,1.648031,1.710030,True,False,False,False

In [18]:
unique_cities = clients["місто_доставки"].nunique()
dummy_columns = city_dummies.shape[1]

print("Кількість унікальних міст:", unique_cities)
print("Кількість нових one-hot стовпців:", dummy_columns)

print(
    "Кількість збігається:",
    unique_cities == dummy_columns
)

Кількість унікальних міст: 4
Кількість нових one-hot стовпців: 4
Кількість збігається: True

Для змінної "місто_доставки" доречно використовувати
one-hot кодування, оскільки міста є номінальними категоріями
і не мають природного порядку.

Якби міста були закодовані числами 1, 2, 3, 4, модель
могла б помилково сприймати ці числа як порядок або
відстань між категоріями.

One-hot кодування створює окремий індикаторний стовпець
для кожного міста і не створює штучного порядку.

Контрольні питання

1. Яка різниця між pd.cut() і pd.qcut()?

pd.cut() ділить діапазон числової змінної на інтервали
однакової або заданої ширини. Кількість спостережень
у таких групах може бути різною.

pd.qcut() використовує квантилі та намагається розподілити
спостереження між групами приблизно порівну. При цьому
ширина інтервалів може бути різною.


2. Чому для міста використовують one-hot кодування?

Місто є номінальною змінною і його категорії не мають
природного порядку.

Якщо закодувати міста числами 1, 2, 3, модель може
помилково вважати, що між ними існує порядок.

One-hot кодування створює незалежний індикатор для кожного
міста і не вносить хибного порядку.


3. Навіщо масштабувати змінні?

Змінні можуть мати різний масштаб. Наприклад, вік має
значення приблизно від 18 до 70, а дохід — десятки тисяч
гривень.

У методах, чутливих до масштабу, змінна з більшими
числовими значеннями може непропорційно впливати
на результат.

Масштабування приводить змінні до порівнянного масштабу.


4. Чому похідна змінна може бути кориснішою?

Похідна змінна може поєднати інформацію з декількох
початкових змінних та надати їй додатковий зміст.

Наприклад, частка доходу показує не просто суму покупки
або дохід клієнта, а те, наскільки великою є покупка
відносно його доходу.

Тому така змінна дозволяє краще порівнювати поведінку
різних клієнтів.